#pragma once
#include <lvgl.h>

// Glyph-subset fonts generated by lv_font_conv (see gen_fonts.sh + MANIFEST.md).
// Variable names == generated filenames. hero = 84px digits+symbols; disp = 30px full ASCII;
// body = 18px full ASCII; mono = 15px full ASCII (JetBrains Mono, shared by all themes).
// Single-theme catalog (editorial): Space Grotesk for hero/display/body, JetBrains Mono for mono.
// The Rajdhani / Doto / Chakra Petch / Pixelify / Inter subsets and the jbm hero/display/body sizes
// were deleted with their themes -- regenerate via gen_fonts.sh if a theme is re-added.
extern const lv_font_t font_sg_hero, font_sg_disp, font_sg_body;   // Space Grotesk
extern const lv_font_t font_jbm_mono;                              // JetBrains Mono
